### ISSUE TITLE
500 error (decoding Unicode is not supported) on OPTIONS request using JS libs

### ISSUE THREAD

**Issue by flyte** [cenobites/flask-jsonrpc#49]
Hi,

When calling the API from either of these two JS libraries:
- https://github.com/Textalk/jquery.jsonrpcclient.js
- https://github.com/datagraph/jquery-jsonrpc

I get a 500 error returned and a traceback looking like this:

```
[2016-08-19 12:35:59,471] ERROR in app: Exception on /api [OPTIONS]
Traceback (most recent call last):
  File "/home/flyte/.virtualenvs/herkulex/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/flyte/.virtualenvs/herkulex/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/flyte/.virtualenvs/herkulex/local/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/flyte/.virtualenvs/herkulex/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/flyte/.virtualenvs/herkulex/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/flyte/.virtualenvs/herkulex/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/flyte/.virtualenvs/herkulex/local/lib/python2.7/site-packages/flask_jsonrpc/__init__.py", line 163, in wrapper
    response_obj, status_code = site.dispatch(request, method)
  File "/home/flyte/.virtualenvs/herkulex/local/lib/python2.7/site-packages/flask_jsonrpc/site.py", line 362, in dispatch
    raw_data = extract_raw_data_request(request)
  File "/home/flyte/.virtualenvs/herkulex/local/lib/python2.7/site-packages/flask_jsonrpc/helpers.py", line 82, in extract_raw_data_request
    return text_type(raw_data, encoding)
TypeError: decoding Unicode is not supported
127.0.0.1 - - [19/Aug/2016 12:35:59] "OPTIONS /api HTTP/1.1" 500 -
```

I'm able to consume the API fine using the Python ServiceProxy.

Is this intended behavior? If so, how do I stop the JS clients from using Unicode?

Thank you.

**Comment by flyte** [comment]
I should mention that this is using Python 2.7.

```python
text_type(u"", "utf-8")
*** TypeError: decoding Unicode is not supported
text_type("", "utf-8")
u''
```

**Comment by flyte** [comment]
This "fixes" the problem I'm having, but I don't know whether it causes others.. Also see comments.

```python
def extract_raw_data_request(request):
    def _extract_raw_data_request(request):
        if request.method == 'GET':
            return request.query_string
        elif request.method == 'POST':
            if request.data:
                return request.data
            elif request.form.to_dict():
                return list(request.form.to_dict().keys())[0]
        return b('')
    raw_data = _extract_raw_data_request(request)

    tried_encodings = []

    # Try charset from content-type
    encoding = request.charset if request.charset else 'utf-8'

    if encoding:  # This will always evaluate to True since if request.charset is Falsy, encoding will become 'utf-8'
        try:
            if isinstance(raw_data, text_type):  # Potential fix?
                return raw_data
            return text_type(raw_data, encoding)
        except UnicodeError:
            tried_encodings.append(encoding)  # This doesn't get used anywhere?

    # Fall back:
    try:
        return text_type(raw_data, encoding, errors='replace')
    except TypeError:
        return raw_data
```

**Comment by flyte** [comment]
Another curiosity:

```python
def extract_raw_data_request(request):
    def _extract_raw_data_request(request):
        if request.method == 'GET':
            return request.query_string
        elif request.method == 'POST':
            if request.data:
                return request.data
            elif request.form.to_dict():
                return list(request.form.to_dict().keys())[0]
        return b('')
    raw_data = _extract_raw_data_request(request)

    print "Received raw_data of type %s" % type(raw_data)
...
```

Results in the following output when called from the JS libs (does OPTIONS first, then POST):
```
Received raw_data of type <type 'unicode'>
127.0.0.1 - - [19/Aug/2016 15:09:21] "OPTIONS /api HTTP/1.1" 200 -
Received raw_data of type <type 'str'>
127.0.0.1 - - [19/Aug/2016 15:09:21] "POST /api HTTP/1.1" 200 -
```

**Comment by nycholas** [comment]
You can send calls via curl?

Thank you.
