### ISSUE TITLE
After version 1.0.* not work batch request

### ISSUE THREAD

**Issue by RemiZOffAlex** [cenobites/flask-jsonrpc#80]
Not work batch request

```
curl -i -X POST \
       -H "Content-Type: application/json; indent=4" \
       -d '[{"jsonrpc":"2.0","method":"App.index","params":{},"id":1},{"jsonrpc":"2.0","method":"App.index","params":{},"id":1}]' http://localhost:5000/api
```

```
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Type: text/html
Content-Length: 141

<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

Error

```
[2020-08-17 23:48:13 +0300] [1323067] [ERROR] Error handling request /api
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_jsonrpc/site.py", line 89, in dispatch_request
    return self.dispatch(json_data)
  File "/usr/local/lib/python3.8/site-packages/flask_jsonrpc/site.py", line 128, in dispatch
    raise InvalidRequestError(data={'message': 'Invalid JSON: {0}'.format(req_json)})
flask_jsonrpc.exceptions.InvalidRequestError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_jsonrpc/views.py", line 44, in dispatch_request
    response, status_code, headers = self.jsonrpc_site.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask_jsonrpc/site.py", line 94, in dispatch_request
    'id': json_data.get('id'),
AttributeError: 'list' object has no attribute 'get'
```

**Comment by nycholas** [comment]
Hi,

Oops, this is a missing... 
We will implement as soon as possible, sorry for that.

Thank you.
