### ISSUE TITLE
ImportError: cannot import name 'Literal'

### ISSUE THREAD

**Issue by staugur** [cenobites/flask-jsonrpc#82]
Hello, thanks for your project.

I am going to use this project and I am testing it now, but I found this error when running `run.py` in the repository:

```
Traceback (most recent call last):
  File "/root/flask-jsonrpc/flask_jsonrpc/types.py", line 35, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 31, in <module>
    from flask_jsonrpc import JSONRPC
  File "/root/flask-jsonrpc/flask_jsonrpc/__init__.py", line 28, in <module>
    from .app import JSONRPC
  File "/root/flask-jsonrpc/flask_jsonrpc/app.py", line 32, in <module>
    from .globals import default_jsonrpc_site, default_jsonrpc_site_api
  File "/root/flask-jsonrpc/flask_jsonrpc/globals.py", line 30, in <module>
    from .site import JSONRPCSite
  File "/root/flask-jsonrpc/flask_jsonrpc/site.py", line 37, in <module>
    from .helpers import get, from_python_type
  File "/root/flask-jsonrpc/flask_jsonrpc/helpers.py", line 32, in <module>
    from .types import Types, Object
  File "/root/flask-jsonrpc/flask_jsonrpc/types.py", line 37, in <module>
    from typing import Literal  # type: ignore  # pylint: disable=C0412
ImportError: cannot import name 'Literal'
```

Python 3.6.7(wsl, virtualenv), Flask-JSONRPC 1.1.0 and master branch.

I found that an exception occurred when importing `flask_jsonrpc/types.py`.

According to [document](https://docs.python.org/3/library/typing.html#typing.Literal), `Literal` is newly added in py3.8, so raise an error.

But in the README and setup.py, the project description is to support py3.6 ?

By the way, `types.Final` is also new in py3.8

**Comment by nycholas** [comment]
Hi,

On this part of code:

`
# Python 3.8+
try:
    from typing_extensions import Literal
except ImportError:  # pragma: no cover
    from typing import Literal  # type: ignore  # pylint: disable=C0412
`

It's missing about the dependence[1] for Python < 3.8, try install the typing-extensions:

`
pip install typing-extensions
`


Let me know if works. please.


[1] - https://pypi.org/project/typing-extensions/


Thank you.

**Comment by staugur** [comment]
Greating! Run OK.(Thanks)

**Comment by nycholas** [comment]
Running tests on Python 3.6, 3.7 and 3.8.

```
$ docker-compose -f docker-compose.test.yml up
Recreating flask-jsonrpc_python3.8_1 ... done
Recreating flask-jsonrpc_python3.7_1 ... done
Recreating flask-jsonrpc_python3.6_1 ... done
Attaching to flask-jsonrpc_python3.7_1, flask-jsonrpc_python3.6_1, flask-jsonrpc_python3.8_1
python3.7_1  | 
python3.7_1  | ------------------------------------
python3.7_1  | Your code has been rated at 10.00/10
python3.7_1  | 
python3.8_1  | 
python3.8_1  | ------------------------------------
python3.8_1  | Your code has been rated at 10.00/10
python3.8_1  | 
python3.6_1  | 
python3.6_1  | ------------------------------------
python3.6_1  | Your code has been rated at 10.00/10
python3.6_1  | 
python3.7_1  | ============================= test session starts ==============================
python3.7_1  | platform linux -- Python 3.7.5, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
python3.7_1  | rootdir: /code, configfile: setup.cfg, testpaths: tests, flask_jsonrpc
python3.7_1  | plugins: typeguard-2.9.1, sugar-0.9.4, cov-2.10.1
python3.7_1  | collected 50 items
python3.7_1  | 
python3.6_1  | ============================= test session starts ==============================
python3.6_1  | platform linux -- Python 3.6.12, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
python3.6_1  | rootdir: /code, configfile: setup.cfg, testpaths: tests, flask_jsonrpc
python3.6_1  | plugins: typeguard-2.9.1, sugar-0.9.4, cov-2.10.1
python3.7_1  | tests/test_app.py ..........                                             [ 20%]
python3.7_1  | tests/test_client.py ..................                                  [ 56%]
python3.7_1  | tests/test_exceptions.py ........                                        [ 72%]
python3.7_1  | tests/test_helpers.py ..                                                 [ 76%]
python3.7_1  | tests/test_types.py ....                                                 [ 84%]
python3.7_1  | tests/test_typing_inspect.py .                                           [ 86%]
python3.6_1  | collected 50 items
python3.6_1  | 
python3.7_1  | tests/contrib/test_browse.py ....                                        [ 94%]
python3.6_1  | tests/test_app.py ..........                                             [ 20%]
python3.7_1  | flask_jsonrpc/helpers.py ...                                             [100%]
python3.7_1  | 
python3.7_1  | =============================== warnings summary ===============================
python3.7_1  | /usr/local/lib/python3.7/site-packages/_pytest/config/__init__.py:1148
python3.7_1  |   /usr/local/lib/python3.7/site-packages/_pytest/config/__init__.py:1148: PytestConfigWarning: Unknown config ini key: python_paths
python3.7_1  |   
python3.7_1  |     self._warn_or_fail_if_strict("Unknown config ini key: {}\n".format(key))
python3.7_1  | 
python3.7_1  | tests/test_app.py::test_app_create
python3.7_1  |   /usr/local/lib/python3.7/site-packages/typeguard/__init__.py:834: UserWarning: no type annotations present -- not typechecking tests.test_app.test_app_create.<locals>.fn0
python3.7_1  |     warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
python3.7_1  | 
python3.7_1  | tests/test_app.py::test_app_create_with_method_without_annotation_on_params
python3.7_1  |   /usr/local/lib/python3.7/site-packages/typeguard/__init__.py:834: UserWarning: no type annotations present -- not typechecking tests.test_app.test_app_create_with_method_without_annotation_on_params.<locals>.fn4
python3.7_1  |     warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
python3.7_1  | 
python3.7_1  | -- Docs: https://docs.pytest.org/en/stable/warnings.html
python3.7_1  | 
python3.7_1  | ----------- coverage: platform linux, python 3.7.5-final-0 -----------
python3.7_1  | Name                                       Stmts   Miss Branch BrPart  Cover
python3.7_1  | ----------------------------------------------------------------------------
python3.7_1  | flask_jsonrpc/__init__.py                      4      0      0      0   100%
python3.7_1  | flask_jsonrpc/app.py                          34      0      4      0   100%
python3.7_1  | flask_jsonrpc/blueprints.py                   13      0      0      0   100%
python3.7_1  | flask_jsonrpc/contrib/__init__.py              0      0      0      0   100%
python3.7_1  | flask_jsonrpc/contrib/browse/__init__.py      31      0      6      0   100%
python3.7_1  | flask_jsonrpc/exceptions.py                   46      0     10      0   100%
python3.7_1  | flask_jsonrpc/globals.py                       5      0      0      0   100%
python3.7_1  | flask_jsonrpc/helpers.py                      30      0     14      0   100%
python3.7_1  | flask_jsonrpc/site.py                        122      0     38      0   100%
python3.7_1  | flask_jsonrpc/types.py                        68      0     26      0   100%
python3.7_1  | flask_jsonrpc/typing_inspect.py                8      0      0      0   100%
python3.7_1  | flask_jsonrpc/views.py                        18      0      2      0   100%
python3.7_1  | flask_jsonrpc/wrappers.py                     49      0     14      0   100%
python3.7_1  | ----------------------------------------------------------------------------
python3.7_1  | TOTAL                                        428      0    114      0   100%
python3.7_1  | Coverage HTML written to dir htmlcov
python3.7_1  | 
python3.7_1  | ======================== 50 passed, 3 warnings in 1.45s ========================
python3.6_1  | tests/test_client.py ..................                                  [ 56%]
python3.6_1  | tests/test_exceptions.py ........                                        [ 72%]
python3.6_1  | tests/test_helpers.py ..                                                 [ 76%]
python3.6_1  | tests/test_types.py .ss.                                                 [ 84%]
python3.6_1  | tests/test_typing_inspect.py .                                           [ 86%]
flask-jsonrpc_python3.7_1 exited with code 0
python3.6_1  | tests/contrib/test_browse.py ....                                        [ 94%]
python3.6_1  | flask_jsonrpc/helpers.py ...                                             [100%]
python3.6_1  | 
python3.6_1  | =============================== warnings summary ===============================
python3.6_1  | /usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py:1148
python3.6_1  |   /usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py:1148: PytestConfigWarning: Unknown config ini key: python_paths
python3.6_1  |   
python3.6_1  |     self._warn_or_fail_if_strict("Unknown config ini key: {}\n".format(key))
python3.6_1  | 
python3.6_1  | tests/test_app.py::test_app_create
python3.6_1  |   /usr/local/lib/python3.6/site-packages/typeguard/__init__.py:834: UserWarning: no type annotations present -- not typechecking tests.test_app.test_app_create.<locals>.fn0
python3.6_1  |     warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
python3.6_1  | 
python3.6_1  | tests/test_app.py::test_app_create_with_method_without_annotation_on_params
python3.6_1  |   /usr/local/lib/python3.6/site-packages/typeguard/__init__.py:834: UserWarning: no type annotations present -- not typechecking tests.test_app.test_app_create_with_method_without_annotation_on_params.<locals>.fn4
python3.6_1  |     warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
python3.6_1  | 
python3.6_1  | -- Docs: https://docs.pytest.org/en/stable/warnings.html
python3.6_1  | 
python3.6_1  | ---------- coverage: platform linux, python 3.6.12-final-0 -----------
python3.6_1  | Name                                       Stmts   Miss Branch BrPart  Cover
python3.6_1  | ----------------------------------------------------------------------------
python3.6_1  | flask_jsonrpc/__init__.py                      4      0      0      0   100%
python3.6_1  | flask_jsonrpc/app.py                          34      0      4      0   100%
python3.6_1  | flask_jsonrpc/blueprints.py                   13      0      0      0   100%
python3.6_1  | flask_jsonrpc/contrib/__init__.py              0      0      0      0   100%
python3.6_1  | flask_jsonrpc/contrib/browse/__init__.py      31      0      6      0   100%
python3.6_1  | flask_jsonrpc/exceptions.py                   46      0     10      0   100%
python3.6_1  | flask_jsonrpc/globals.py                       5      0      0      0   100%
python3.6_1  | flask_jsonrpc/helpers.py                      30      0     14      0   100%
python3.6_1  | flask_jsonrpc/site.py                        122      0     38      0   100%
python3.6_1  | flask_jsonrpc/types.py                        68      8     26      4    87%
python3.6_1  | flask_jsonrpc/typing_inspect.py                8      0      0      0   100%
python3.6_1  | flask_jsonrpc/views.py                        18      0      2      0   100%
python3.6_1  | flask_jsonrpc/wrappers.py                     49      0     14      0   100%
python3.6_1  | ----------------------------------------------------------------------------
python3.6_1  | TOTAL                                        428      8    114      4    98%
python3.6_1  | Coverage HTML written to dir htmlcov
python3.6_1  | 
python3.6_1  | ================== 48 passed, 2 skipped, 3 warnings in 1.74s ===================
flask-jsonrpc_python3.6_1 exited with code 0
python3.8_1  | Success: no issues found in 13 source files
python3.8_1  | ============================= test session starts ==============================
python3.8_1  | platform linux -- Python 3.8.3, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
python3.8_1  | rootdir: /code, configfile: setup.cfg, testpaths: tests, flask_jsonrpc
python3.8_1  | plugins: typeguard-2.9.1, sugar-0.9.4, cov-2.10.1
python3.8_1  | collected 50 items
python3.8_1  | 
python3.8_1  | tests/test_app.py ..........                                             [ 20%]
python3.8_1  | tests/test_client.py ..................                                  [ 56%]
python3.8_1  | tests/test_exceptions.py ........                                        [ 72%]
python3.8_1  | tests/test_helpers.py ..                                                 [ 76%]
python3.8_1  | tests/test_types.py ....                                                 [ 84%]
python3.8_1  | tests/test_typing_inspect.py .                                           [ 86%]
python3.8_1  | tests/contrib/test_browse.py ....                                        [ 94%]
python3.8_1  | flask_jsonrpc/helpers.py ...                                             [100%]
python3.8_1  | 
python3.8_1  | =============================== warnings summary ===============================
python3.8_1  | /usr/local/lib/python3.8/site-packages/_pytest/config/__init__.py:1148
python3.8_1  |   /usr/local/lib/python3.8/site-packages/_pytest/config/__init__.py:1148: PytestConfigWarning: Unknown config ini key: python_paths
python3.8_1  |   
python3.8_1  |     self._warn_or_fail_if_strict("Unknown config ini key: {}\n".format(key))
python3.8_1  | 
python3.8_1  | tests/test_app.py::test_app_create
python3.8_1  |   /usr/local/lib/python3.8/site-packages/typeguard/__init__.py:834: UserWarning: no type annotations present -- not typechecking tests.test_app.test_app_create.<locals>.fn0
python3.8_1  |     warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
python3.8_1  | 
python3.8_1  | tests/test_app.py::test_app_create_with_method_without_annotation_on_params
python3.8_1  |   /usr/local/lib/python3.8/site-packages/typeguard/__init__.py:834: UserWarning: no type annotations present -- not typechecking tests.test_app.test_app_create_with_method_without_annotation_on_params.<locals>.fn4
python3.8_1  |     warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
python3.8_1  | 
python3.8_1  | -- Docs: https://docs.pytest.org/en/stable/warnings.html
python3.8_1  | 
python3.8_1  | ----------- coverage: platform linux, python 3.8.3-final-0 -----------
python3.8_1  | Name                                       Stmts   Miss Branch BrPart  Cover
python3.8_1  | ----------------------------------------------------------------------------
python3.8_1  | flask_jsonrpc/__init__.py                      4      0      0      0   100%
python3.8_1  | flask_jsonrpc/app.py                          34      0      4      0   100%
python3.8_1  | flask_jsonrpc/blueprints.py                   13      0      0      0   100%
python3.8_1  | flask_jsonrpc/contrib/__init__.py              0      0      0      0   100%
python3.8_1  | flask_jsonrpc/contrib/browse/__init__.py      31      0      6      0   100%
python3.8_1  | flask_jsonrpc/exceptions.py                   46      0     10      0   100%
python3.8_1  | flask_jsonrpc/globals.py                       5      0      0      0   100%
python3.8_1  | flask_jsonrpc/helpers.py                      30      0     14      0   100%
python3.8_1  | flask_jsonrpc/site.py                        122      0     38      0   100%
python3.8_1  | flask_jsonrpc/types.py                        68      0     26      0   100%
python3.8_1  | flask_jsonrpc/typing_inspect.py                8      0      0      0   100%
python3.8_1  | flask_jsonrpc/views.py                        18      0      2      0   100%
python3.8_1  | flask_jsonrpc/wrappers.py                     49      0     14      0   100%
python3.8_1  | ----------------------------------------------------------------------------
python3.8_1  | TOTAL                                        428      0    114      0   100%
python3.8_1  | Coverage HTML written to dir htmlcov
python3.8_1  | 
python3.8_1  | Required test coverage of 100% reached. Total coverage: 100.00%
python3.8_1  | ======================== 50 passed, 3 warnings in 1.47s ========================
flask-jsonrpc_python3.8_1 exited with code 0
```
