### ISSUE TITLE
Can not import JSONRPC in python3.7 or 3.6 due to  types

### ISSUE THREAD

**Issue by manortec** [cenobites/flask-jsonrpc#86]
Traceback (most recent call last):
  File "/home/myuser/haoyidian/baike/venv/lib/python3.7/site-packages/flask_jsonrpc/types.py", line 35, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 8, in <module>
    from h5 import app
  File "/home/myuser/haoyidian/baike/h5/app.py", line 10, in <module>
    from flask_jsonrpc import JSONRPC
  File "/home/myuser/haoyidian/baike/venv/lib/python3.7/site-packages/flask_jsonrpc/__init__.py", line 28, in <module>
    from .app import JSONRPC
  File "/home/myuser/haoyidian/baike/venv/lib/python3.7/site-packages/flask_jsonrpc/app.py", line 32, in <module>
    from .globals import default_jsonrpc_site, default_jsonrpc_site_api
  File "/home/myuser/haoyidian/baike/venv/lib/python3.7/site-packages/flask_jsonrpc/globals.py", line 30, in <module>
    from .site import JSONRPCSite
  File "/home/myuser/haoyidian/baike/venv/lib/python3.7/site-packages/flask_jsonrpc/site.py", line 37, in <module>
    from .helpers import get, from_python_type
  File "/home/myuser/haoyidian/baike/venv/lib/python3.7/site-packages/flask_jsonrpc/helpers.py", line 32, in <module>
    from .types import Types, Object
  File "/home/myuser/haoyidian/baike/venv/lib/python3.7/site-packages/flask_jsonrpc/types.py", line 37, in <module>
    from typing import Literal  # type: ignore  # pylint: disable=C0412
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)

**Comment by manortec** [comment]
It could import JSONRPC  porperly in python3.8,but not 3.7 or 3.6

**Comment by nycholas** [comment]
Hi,

Try to used master version, in this PR[1], we added this dependencies.


[1] - https://github.com/cenobites/flask-jsonrpc/pull/83

**Comment by manortec** [comment]
@nycholas Thanks!  Yes,it works when I used the master version. Before,I used the version on pipy,and that version was not up to date.

**Comment by mrJeppard** [comment]
This solution worked for me with an additional `pip install typing-inspect` in python 3.7.3. Not sure if this is something wrong with the setup.py or a problem specific to a python version range including 3.7.3, but thought I'd leave a note in case it is helpful.

**Comment by nycholas** [comment]
@mrJeppard yes, it have a problem with setup.py... the depence `typing-inspect` was added[1][2] after and I didn't update setup.py with them. Let be free to create a new pull request with this modification.

Thank you.

[1] - https://github.com/cenobites/flask-jsonrpc/blob/master/requirements.pip#L10
[2] - https://github.com/cenobites/flask-jsonrpc/commit/a63b126dfa8e344cb6c5e85767b0c6507393c614
